// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// wang_paired_ci_cpp
NumericVector wang_paired_ci_cpp(int n10, int t, int n01, double conf_level, std::string ci_type, double precision, int grid_one, int grid_two);
RcppExport SEXP _ibist_wang_paired_ci_cpp(SEXP n10SEXP, SEXP tSEXP, SEXP n01SEXP, SEXP conf_levelSEXP, SEXP ci_typeSEXP, SEXP precisionSEXP, SEXP grid_oneSEXP, SEXP grid_twoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n10(n10SEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type n01(n01SEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    Rcpp::traits::input_parameter< std::string >::type ci_type(ci_typeSEXP);
    Rcpp::traits::input_parameter< double >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< int >::type grid_one(grid_oneSEXP);
    Rcpp::traits::input_parameter< int >::type grid_two(grid_twoSEXP);
    rcpp_result_gen = Rcpp::wrap(wang_paired_ci_cpp(n10, t, n01, conf_level, ci_type, precision, grid_one, grid_two));
    return rcpp_result_gen;
END_RCPP
}
// wang_paired_lower_all_cpp
NumericVector wang_paired_lower_all_cpp(int n, double conf_level, double precision, int grid_one, int grid_two);
RcppExport SEXP _ibist_wang_paired_lower_all_cpp(SEXP nSEXP, SEXP conf_levelSEXP, SEXP precisionSEXP, SEXP grid_oneSEXP, SEXP grid_twoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    Rcpp::traits::input_parameter< double >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< int >::type grid_one(grid_oneSEXP);
    Rcpp::traits::input_parameter< int >::type grid_two(grid_twoSEXP);
    rcpp_result_gen = Rcpp::wrap(wang_paired_lower_all_cpp(n, conf_level, precision, grid_one, grid_two));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ibist_wang_paired_ci_cpp", (DL_FUNC) &_ibist_wang_paired_ci_cpp, 8},
    {"_ibist_wang_paired_lower_all_cpp", (DL_FUNC) &_ibist_wang_paired_lower_all_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ibist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
