# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wang_paired_ci_cpp <- function(n10, t, n01, conf_level = 0.95, ci_type = "Two.sided", precision = 0.00001, grid_one = 30L, grid_two = 20L) {
    .Call(`_ibist_wang_paired_ci_cpp`, n10, t, n01, conf_level, ci_type, precision, grid_one, grid_two)
}

wang_paired_lower_all_cpp <- function(n, conf_level = 0.95, precision = 0.00001, grid_one = 30L, grid_two = 20L) {
    .Call(`_ibist_wang_paired_lower_all_cpp`, n, conf_level, precision, grid_one, grid_two)
}

